CREATE DATABASE IF NOT EXISTS logDb;
USE logDb;
CREATE TABLE IF NOT EXISTS logs
   (
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(20)    NOT NULL,
    DATED   VARCHAR(20)    NOT NULL,
    LOGGER  VARCHAR(50)    NOT NULL,
    LEVEL   VARCHAR(10)    NOT NULL,
    MESSAGE VARCHAR(1000)  NOT NULL,
    PRIMARY KEY (id)
   );
