version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    volumes:
      - data:/data
    ports: 
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  image-object-service:
    build: .
    ports:
      - "8000:8000"
    volumes: 
      - "./src:/usr/app/src"
    depends_on: 
      - minio

volumes:
  data:
