version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2020-10-28T08-16-50Z
    volumes:
      - data:/data
    ports: 
      - "9000:${MINIO_PORT}"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  image-object-service:
    build: .
    ports:
      - "8000:${PORT}"
    volumes: 
      - "./src:/usr/app/src"
    depends_on: 
      - minio

volumes:
  data:
